# Generated by Django 3.2.8 on 2021-10-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('born', models.CharField(max_length=100)),
                ('batting_style', models.CharField(max_length=100)),
                ('bowling_style', models.CharField(max_length=100)),
                ('first_Test', models.TextField()),
                ('first_Odi', models.TextField()),
                ('first_T20', models.TextField()),
                ('profile', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'verbose_name_plural': 'players',
            },
        ),
    ]
