# Generated by Django 3.2.8 on 2021-10-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_detail', models.TextField()),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('mom', models.CharField(max_length=100)),
                ('bom', models.CharField(blank=True, max_length=100, null=True)),
                ('best_fielder', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
    ]
